server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    active: dev # 默认启动 dev 环境
  application:
    name: yiqilian-biz-auth
  
  # 临时关闭数据库连接检查（因为还没配置真实的 MySQL）
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
