<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.yiqilian</groupId>
        <artifactId>yiqilian-backend</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath> </parent>

    <artifactId>biz-auth</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.yiqilian</groupId>
            <artifactId>yiqilian-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.yiqilian</groupId>
            <artifactId>yiqilian-model</artifactId>
        </dependency>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <scope>runtime</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>